# Generated by Django 4.2.3 on 2023-07-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, unique=True, verbose_name='Заголовок')),
                ('content', models.CharField(max_length=300, verbose_name='Описание')),
                ('img', models.FileField(default='', upload_to='img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='Sertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('img', models.FileField(default='', upload_to='img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(default='', max_length=300, verbose_name='Длина')),
                ('width', models.CharField(default='', max_length=300, verbose_name='Ширина')),
                ('heit', models.CharField(default='', max_length=300, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталог',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('img', models.FileField(default='', upload_to='img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Наше производство',
                'verbose_name_plural': 'Наше производство',
            },
        ),
    ]
