# Generated by Django 4.2.3 on 2023-07-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sertificate',
            options={'verbose_name': 'Сертификат', 'verbose_name_plural': 'Сертификаты'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размерный ряд', 'verbose_name_plural': 'Размерные ряды'},
        ),
    ]
