# Generated by Django 4.2.3 on 2023-07-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_sertificate_options_alter_size_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='img',
            field=models.ImageField(default='', upload_to='img', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='sertificate',
            name='img',
            field=models.ImageField(default='', upload_to='img', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(default='', upload_to='img', verbose_name='Картинка'),
        ),
    ]
