# Generated by Django 4.2.3 on 2023-07-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_catalog_img_alter_sertificate_img_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name': 'Размерный ряд', 'verbose_name_plural': 'Размерные ряд'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='content',
            field=models.CharField(max_length=300, verbose_name='Габариты'),
        ),
    ]
