# Generated by Django 4.2.3 on 2023-07-19 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_size_options_alter_catalog_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='content',
        ),
        migrations.CreateModel(
            name='CatalogSizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=300, verbose_name='Габариты')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catalog', verbose_name='Каталог')),
            ],
            options={
                'verbose_name': 'Габариты',
                'verbose_name_plural': 'Габариты',
            },
        ),
    ]
