# Generated by Django 4.2.3 on 2023-07-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_catalog_content_catalogsizes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogsizes',
            options={'verbose_name': 'Габарит', 'verbose_name_plural': 'Габариты'},
        ),
    ]
