# Generated by Django 4.2.3 on 2023-07-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_catalogsizes_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=300, verbose_name='Название')),
                ('img', models.ImageField(default='', upload_to='img', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'О нас (картинки)',
                'verbose_name_plural': 'О нас (картинки)',
            },
        ),
    ]
