# Generated by Django 4.2.3 on 2023-07-19 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogsizes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.catalog', to_field='title', verbose_name='Каталог'),
        ),
    ]
