# Generated by Django 4.2.3 on 2023-07-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_catalog_content_delete_catalogsizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='content',
            field=models.CharField(default='', help_text='Через зяпятую', max_length=300, unique=True, verbose_name='Габариты'),
        ),
    ]
